# site settings
title: Jeffrey Kola
subtitle: Projects, Experiences and more...
email: jeffreykola15@gmail.com
description: If they don't know your dreams then they can't shoot your down
baseurl: "./" # the subpath of your site, e.g. /blog
url: "https://jeffreykola.github.io/" # the base hostname & protocol for your site
author: "Jeffrey Kola-Abodunde"
country: United Kingdom

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
linkedin_url: https://www.linkedin.com/in/jeffreykola

# build settings
markdown: kramdown

sass:
  style: compressed
